[tool.poetry]
name = "ac-car"
version = "0.1.0"
description = ""
authors = ["Benedikt Huff <benedikt.huff@htlstp.at>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
